package tech.fastj.input.keyboard;

/**
 * A keyboard action listener.
 *
 * <b>NOTE:</b> For use with a FastJ {@code Scene}, a keyboard action listener must be added to a
 * {@code Scene}'s list of keyboard action listeners.
 * <br>
 * If you are planning to implement this class into a separate usage, you may consider using the {@code InputManager}
 * class to store a list of keyboard action listeners. Then, have events from a class extending {@code KeyListener}
 * fired to that {@code InputManager}.
 *
 * @author Andrew Dey
 * @version 1.0.0
 */
public interface KeyboardActionListener {

    /** Event called when a key is currently pressed, once per game update. */
    default void onKeyDown() {
    }

    /**
     * Event called when a key was recently pressed.
     *
     * @param keyboardEvent The key event generated by the recent key press.
     */
    default void onKeyRecentlyPressed(KeyboardStateEvent keyboardEvent) {
    }

    /**
     * Event called when a key was recently released.
     *
     * @param keyboardEvent The key event generated by the recent key release.
     */
    default void onKeyReleased(KeyboardStateEvent keyboardEvent) {
    }

    /**
     * Event called when a key was recently typed.
     *
     * @param keyboardEvent The key event generated by the recent key type.
     */
    default void onKeyTyped(KeyboardTypedEvent keyboardEvent) {
    }
}
