package io.github.lucasstarsz.fastj.engine.io.listeners;

import java.awt.event.KeyEvent;

/**
 * A keyboard action listener.
 *
 * <b>NOTE:</b> For use with a FastJ {@code Scene}, a keyboard action listener must be added to a
 * {@code Scene}'s list of keyboard action listeners.
 * <br>
 * If you are planning to implement this class into a separate usage, you may consider using the {@code InputManager}
 * class to store a list of keyboard action listeners. Then, have events from a class extending {@code KeyListener}
 * fired to that {@code InputManager}.
 *
 * @author Andrew Dey
 * @version 0.3.2a
 * @see io.github.lucasstarsz.fastj.engine.systems.game.Scene
 * @see io.github.lucasstarsz.fastj.engine.systems.input.InputManager
 * @see java.awt.event.KeyListener
 */
public interface KeyboardActionListener {

    /** Event called when a key is currently pressed, once per game update. */
    default void onKeyDown() {
    }

    /**
     * Event called when a key was recently pressed.
     *
     * @param keyEvent The key event generated by the recent key press.
     */
    default void onKeyRecentlyPressed(KeyEvent keyEvent) {
    }

    /**
     * Event called when a key was recently released.
     *
     * @param keyEvent The key event generated by the recent key release.
     */
    default void onKeyReleased(KeyEvent keyEvent) {
    }

    /**
     * Event called when a key was recently typed.
     *
     * @param keyEvent The key event generated by the recent key type.
     */
    default void onKeyTyped(KeyEvent keyEvent) {
    }
}
