name: Bug Report
description: "Something not working? Let us know!"
title: "[Bug]: "
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making the effort to point out issues in FastJ! We really appreciate it.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Describe in detail, if you can.
      placeholder: Tell us what you were trying to do, and what went wrong!
    validations:
      required: true
  - type: textarea
    id: reproduce-error
    attributes:
      label: How to Reproduce the Error
      description: "Walk us through the error, step by step."
      value: |
        1. 
        2. 
        3.
        ...
      render: bash
    validations:
      required: true
  - type: dropdown
    id: fastj-version
    attributes:
      label: FastJ Version
      description: What version(s) of FastJ are you having issues with?
      multiple: true
      options:
        - 1.6.0 (Latest Version)
        - 1.5.1
        - 1.5.0
        - 1.4.0
        - snapshot (please specify below)
        - other (please specify below)
    validations:
      required: true
  - type: input
    id: fastj-version-specific
    attributes:
      label: Specific FastJ Version
      description: Using a specific version of FastJ? Specify it here!
      placeholder: e.g. FastJ 1.6.0-SNAPSHOT-1
  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: What version(s) of Java are you seeing this on?
      multiple: true
      options:
        - Java 11
        - Java 12-15
        - Java 16
        - Java 17
  - type: textarea
    id: exceptions-and-logs
    attributes:
      label: Relevant Exceptions/Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fastjengine/FastJ/tree/main/.github/CONTRIBUTING.md)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
